### ISSUE TITLE
Python 3.12 - ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by alechouse97** [relf/pyDOE3#12]
Hello, I'm trying to use this package in a python 3.12 environment, but am getting the following error:

```
ModuleNotFoundError: No module named 'imp'
```

It looks like `imp` was dropped in favor of `importlib` in python 3.12. Are there any plans to offer 3.12 compatibility, or any other workarounds?

Thanks!

**Comment by relf** [comment]
Hmmm... Are you sure to use pyDOE**3** ? It looks like a pyDOE2 error.

**Comment by alechouse97** [comment]
You are correct - I still had some pyDOE2 code left behind. Thank you!
