### ISSUE TITLE
Bug in Central Composite Design (CCI) Implementation

### ISSUE THREAD

**Issue by LaurinZubler** [relf/pyDOE3#17]
Hi relf

I believe I've found a bug in the Central Composite Design (CCI) implementation.

In the current code, the variable `a` is used on line 149 before it is defined on line 150 in the `star(n)` function.

```python
# https://github.com/relf/pyDOE3/blob/5302b5d8a3cee0271a42b103cdd053629802c0f7/pyDOE3/doe_composite.py#L146

if face.lower() in ("inscribed", "cci"):
    H1 = ff2n(n)
    H1 = H1 / a  # Scale down the factorial points
    H2, a = star(n)
```

## ~~Suggested Fix:~~
<s> 

The `star(n)` function should be called before attempting to use `a`. Here's the corrected version:
```python
if face.lower() in ("inscribed", "cci"):
    H2, a = star(n)
    H1 = ff2n(n)
    H1 = H1 / a  # Scale down the factorial points
```

</s>

## Test Case
Here is a test case to demonstrate the issue. 

The corner points of an inscribed square within a circle should be approximately:

$$ \pm { \sqrt{2} \over  2 }= \pm {1 \over \sqrt{2} } \approx \pm 0.707$$ 

Using the scaling factor `a` as described in the [NIST Handbook](https://www.itl.nist.gov/div898/handbook/pri/section3/pri3361.htm) should result in the correct coordinates.
```python
def test_cci():
    actual = ccdesign(2, center=[1, 0], face="cci")

    expected = np.array([
        [-0.707, -0.707],
        [-0.707, 0.707],
        [0.707, -0.707],
        [0.707, 0.707],
        [0, 0],
        [-1, 0],
        [1, 0],
        [0, -1],
        [0, 1],
    ])

    assert np.array_equal(np.round(actual, decimals=3), expected)
```

Currently, `ccdesign()` returns the following incorrect result:
```python
[
    [-0.79056942, -0.79056942],
    [-0.79056942, 0.79056942],
    [0.79056942, -0.79056942],
    [0.79056942, 0.79056942],
    [0, 0],
    [-1, 0],
    [1, 0],
    [0, -1],
    [0, 1],
]
```

Thank you for taking a look! Let me know if you need further information.

Best regards,
Laurin

**Comment by LaurinZubler** [comment]
### Update

I attempted to fix the issue myself, but unfortunately, I'm not very familiar with GitHub and don't understand how to push and create a pull request. 

Different than originally thought, I realized that `a` is intended for `H2` and cannot be used for `H1`. I modified the function to:

```python
  if face.lower() in ("inscribed", "cci"):
      H1 = ff2n(n)
      H1 = H1 / 2**(n/4)  # Scale down the factorial points
      H2, a = star(n)
```

The calculation of `a` is now based on the method described in the [NIST Handbook](https://www.itl.nist.gov/div898/handbook/pri/section3/pri3361.htm). 

I have also added this test in `tests/test_composite.py`:
```python
  def test_cci(self):
      actual = ccdesign(2, center=[1, 0], face="cci")

      expected = np.array([
          [-0.707, -0.707],
          [-0.707, 0.707],
          [0.707, -0.707],
          [0.707, 0.707],
          [0, 0],
          [-1, 0],
          [1, 0],
          [0, -1],
          [0, 1],
      ])

      assert np.array_equal(np.round(actual, decimals=3), expected)
```
I believe this is correct, but I could be mistaken. Please check the logic and whether the code adheres to your guidelines.

**Comment by LaurinZubler** [comment]
Hi relf,
thank you for the detailed instructions.  
I’ve reviewed the code and read some DoE literature, here are my findings:

1. The variable `a` is set on line [140](https://github.com/relf/pyDOE3/blob/master/pyDOE3/doe_composite.py#L140) or [144](https://github.com/relf/pyDOE3/blob/master/pyDOE3/doe_composite.py#L144), depending on the value of `alpha`.  Thus, there is no bug regarding `a` not being initialized by line [149](https://github.com/relf/pyDOE3/blob/master/pyDOE3/doe_composite.py#L149).  

2. When I call the function with the parameter `alpha="rotatable"`, I get the expected result of `±0.707`:  
```python
ccdesign(2, center=[1, 0], face="cci", alpha="rotatable")
```
---
So, is this a bug or not? 
I don’t understand the theory well enough to answer definitively. Most literature distinguishes between the three types: `Circumscribed CCC`, `Inscribed CCI`, and `Face Centered CCF`. 
In the [NIST Handbook](https://www.itl.nist.gov/div898/handbook/pri/section3/pri3361.htm), it states: _“Both the CCC and CCI are rotatable designs, but the CCF is not.”_  

On [wikipedia](https://en.wikipedia.org/wiki/Central_composite_design#Choosing_%CE%B1) a distinction is made between `orthogonal` and `rotatable` to calculate `a`. But the 3 types are not mentioned.

Is there a use case for `CCI` and `orthogonal`?
Maybe the default should be `rotatable` when choosing `CCC` and `CCI`? 


I don’t have more to add at this point. It is up to you how to proceed further.

**Comment by relf** [comment]
Thanks for the analysis! To be frank, I am not familiar with the theory neither. As the code is around for years (see pyDOE, pyDOE2), I did not found a related issue in legacy repos, so I won't fix anything or change a default value.
