### ISSUE TITLE
Errors in fracfact_opt

### ISSUE THREAD

**Issue by jvailius** [relf/pyDOE3#9]
Hi @relf,

first of all thank you for keeping pyDOE up-to-date! I have an issue with the function `fracfact_opt` https://github.com/relf/pyDOE3/blob/766e8103f2fadf6e0926568291d5509f2198311f/pyDOE3/doe_factorial.py#L374 

complaining about `n_aliases` being a float instead of an int 
https://github.com/relf/pyDOE3/blob/766e8103f2fadf6e0926568291d5509f2198311f/pyDOE3/doe_factorial.py#L421

and hashing the numpy arrays gives me an error here: https://github.com/relf/pyDOE3/blob/766e8103f2fadf6e0926568291d5509f2198311f/pyDOE3/doe_factorial.py#L506

Not sure what the best solution for hashing is. Maybe just `contrast.tobytes()`?

I use python 3.11.9 and numpy 1.26.4.

**Comment by relf** [comment]
Hi, could you provide the code which shows the issue?

**Comment by jvailius** [comment]
Sorry, forgot to mention it: You can try pretty much anything e.g. `fracfact_opt(4, 1)`

**Comment by relf** [comment]
Actually, I think this function was just never used/tested with Python3.
